title: Hey, I am Aparna Sree, Data Scientist
description: > # this means to ignore newlines until "baseurl:"
  My blog for my ml experiments.
permalink: ':title/'
baseurl: "/mlblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aparna Sree # add your name
author-img: aparna.png # add your photo
about-author: I am a Data Scientist with a passion for learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: aparnasree2020 # add your Github handle
social-linkedin: https://www.linkedin.com/in/aparna-sree/# add your Linkedin handle
social-email: aparnasree11217.blog@gmail.com# add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
